### PR TITLE
Made sure it does not keep instruments selected when switching betwee…

### PR DESCRIPTION
**Pull request by rodrigopavezi**
…n lists

@stulees @tejohnso @settinghead please review.

Card here: https://trello.com/c/CYZAL2v4/3034-issue-financial-selector-100-2

Cheers

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi 👍

**Comment by tejohnso** [comment]
Guess I was too late :)

**Comment by rodrigopavezi** [comment]
@tejohnso that is a good point. I will make the changes in another PR. cheers

**Comment by rodrigopavezi** [comment]
@tejohnso I was looking into changing it but if we stop returning the cached object we loose the caching feature. So I will leave like that for now. cheers

**Pull request merged**
