### PR TITLE
Edit list and instrument names

### PR DESCRIPTION
**Pull request by settinghead**

### CODE REVIEW

**Comment by settinghead** [comment]
@tejohnso please review.
@Rise-Vision/delivery FYI

**Comment by tejohnso** [comment]
@settinghead I think *touchList()* could be used elsewhere since where're putting modby/moddate on everything.  So it might be useful to take it out of that service and make it more generic.  We probably don't need to include permissions checks in it since we're going to be calling it after authorization has already been confirmed.  If for some reason it's called without proper auth and the call fails that should be okay to handle with a simple *console.error*

**Comment by settinghead** [comment]
@tejohnso good suggestion.

I refactored the touch logic into a single factory method `touch()`, with a basic unit test.

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
